# Generated by Django 4.1.2 on 2022-10-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('balance', models.FloatField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='media/account/%y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Caterogies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
